name: "Create GitHub Release"

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go get -t -v ./...
      - run: go test -v -race ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create GitHub Release
        id: create
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}

  upload:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      - name: Download go dependencies
        run: go get -t -v ./...

      - name: Build linux32 Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o DefaultEnv.linux32 DefaultEnv_plugin.go

      - name: Build linux64 Binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o DefaultEnv.linux64 DefaultEnv_plugin.go

      - name: Build win32 Binary
        run: CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -o DefaultEnv.win32 DefaultEnv_plugin.go

      - name: Build win64 Binary
        run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o DefaultEnv.win64 DefaultEnv_plugin.go

      - name: Build osx Binary
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o DefaultEnv.osx DefaultEnv_plugin.go

      - name: Build osxarm Binary
        run: CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o DefaultEnv.osxarm DefaultEnv_plugin.go
        
      - name: Create Checksums
        id: read-shasum
        run: |
          echo "shasum<<EOF" >> $GITHUB_OUTPUT
          shasum -a 1 DefaultEnv.* >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Upload Binaries
        id: upload-release-asset
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            DefaultEnv.linux32
            DefaultEnv.linux64
            DefaultEnv.win32
            DefaultEnv.win64
            DefaultEnv.osx
            DefaultEnv.osxarm
            shasum.txt
          append_body: true
          body: |
            ---
            **SHA-1 Sums:**

            ```
            ${{ steps.read-shasum.outputs.shasum }}
            ```
